substitutions:
  name: !secret name

esphome:
  name: ${name}

bk72xx:
  board: wb3s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} AP"
    password: !secret wifi_fallback_password

captive_portal:

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  password: !secret api_password

#mqtt:
#  broker: !secret mqtt_broker

ota:
  password: !secret ota_password

# Enable Web server.
web_server:
  port: 80

light:
  - platform: monochromatic
    name: Red Nebula
    id: red_nebula
    output: red
    restore_mode: ALWAYS_OFF
  - platform: monochromatic
    name: Green Nebula
    id: green_nebula
    output: green
    restore_mode: ALWAYS_OFF
  - platform: monochromatic
    name: Blue Nebula
    id: blue_nebula
    output: blue
    restore_mode: ALWAYS_OFF
  - platform: monochromatic
    name: Laser
    id: laser
    output: laser_pwm
    restore_mode: ALWAYS_OFF
  - platform: binary
    name: Button LED0
    id: button_led0
    output: button_led0_out
    restore_mode: ALWAYS_OFF
  - platform: monochromatic
    name: Button LED1
    id: button_led1
    output: button_led1_out
    restore_mode: ALWAYS_OFF

fan:
  platform: speed
  name: Motor
  id: motor
  output: motor_pwm
  restore_mode: ALWAYS_OFF

output:
  - platform: libretiny_pwm
    id: red
    pin: P9
    inverted: true
  - platform: libretiny_pwm
    id: green
    pin: P24
    inverted: true
  - platform: libretiny_pwm
    id: blue
    pin: P26
    inverted: true

  - platform: libretiny_pwm
    id: laser_pwm
    pin: P8
    inverted: true
  - platform: libretiny_pwm
    id: motor_pwm
    pin: P6
    min_power: 15%

  - platform: gpio
    id: button_led0_out
    pin: P1
    inverted: true
  - platform: libretiny_pwm
    id: button_led1_out
    pin: P7
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: P14
      mode: INPUT_PULLDOWN_16
      inverted: true
    name: Button
    on_press:
      then:
        - fan.turn_on:
            id: motor
            speed: 100
        - light.turn_on:
            id: laser
            brightness: 65%
        - delay : 1h
        - fan.turn_off:
            id: motor
        - light.turn_off:
            id: laser
