substitutions:
  name: !secret name

esphome:
  name: ${name}

bk72xx:
  board: wb3s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${name} AP"
    password: !secret wifi_fallback_password

captive_portal:

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  password: !secret api_password

#mqtt:
#  broker: !secret mqtt_broker

ota:
  password: !secret ota_password

# Enable Web server.
web_server:
  port: 80

light:
  - platform: rgb
    name: ${name}_light
    id: rgb_light
    red: red
    green: green
    blue: blue
    restore_mode: ALWAYS_OFF
    effects:
      - flicker:
          name: Flicker
          alpha: 95%
          intensity: 2.5%
      - random:
          name: Random
          transition_length: 2.5s
          update_interval: 3s
      - random:
          name: Random Slow
          transition_length: 10s
          update_interval: 5s

  - platform: monochromatic
    name: ${name}_laser
    id: laser
    output: laser_pwm
    restore_mode: ALWAYS_OFF
  - platform: monochromatic
    name: ${name}_bled
    id: bled
    output: bled_pwm
    restore_mode: ALWAYS_OFF
    internal: true
  - platform: monochromatic
    name: ${name}_rled
    id: rled
    output: rled_pwm
    restore_mode: ALWAYS_OFF
    internal: true

fan:
  platform: speed
  name: "${name}_motor"
  id: motor
  output: motor_pwm
  restore_mode: ALWAYS_OFF

output:
  - platform: libretiny_pwm
    id: red
    pin: P9
    inverted: true
  - platform: libretiny_pwm
    id: green
    pin: P24
    inverted: true
  - platform: libretiny_pwm
    id: blue
    pin: P26
    inverted: true

  - platform: libretiny_pwm
    id: laser_pwm
    pin: P8
    # max_power: 80%
    # frequency: 2000 Hz
    inverted: true
  - platform: libretiny_pwm
    id: motor_pwm
    pin: P6
    min_power: 15%

  - platform: libretiny_pwm
    id: bled_pwm
    pin: P1
    inverted: true
  - platform: libretiny_pwm
    id: rled_pwm
    pin: P7
    inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: P14
      mode: INPUT_PULLDOWN_16
      inverted: true
    name: ${name}_button
    on_press:
      then:
        - light.turn_on:
            id: rgb_light
            brightness: 30%
        - light.turn_on:
            id: laser
            brightness: 65%
        - delay : 1h
        - light.turn_off:
            id: rgb_light
        - light.turn_off:
            id: laser

interval:
  - interval: 1s
    then:
      if:
        condition:
          wifi.connected:
        then:
          - light.turn_on:
              id: bled
              brightness: 50%
        else:
          - light.turn_off:
              id: bled
  - interval: 1s
    then:
      if:
        condition:
          api.connected:
        then:
          - light.turn_on:
              id: rled
              brightness: 50%
        else:
          - light.turn_off:
              id: rled
